--- #Handlers task
- hosts: all
  user: root
  connection: ssh

  tasks: 
    - name: Install httpd
      action: yum name=httpd state=installed
      notify: httpd restart

  handlers:
    - name: httpd restart
      action: service name=httpd state=restarted 
